/*
  File autogenerated by gengetopt version 2.23
  generated with the following command:
  gengetopt --input=dinoknot.ggo --c-extension=cc --header-extension=hh --arg-struct-name=args_info --unamed-opts=input

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.hh"

const char *args_info_purpose = "Minimum free energy folding of RNA-RNA, RNA-DNA and DNA-DNA interactions";

const char *args_info_usage = "Usage: DinoKnot [options] [sequence]";

const char *args_info_versiontext = "";

const char *args_info_description = "Read RNA and DNA sequences from cmdline; predict minimum free energy and\noptimum structure\n Give both sequences in 5'-3' format. Place the smaller sequence on the left.";

const char *args_info_help[] = {
  "  -h, --help                 Print help and exit",
  "  -V, --version              Print version and exit",
  "      --s1=STRING            Specify the first sequence",
  "      --s2=STRING            Specify the second sequence",
  "      --r1=STRING            Specify the pseuodoknot-free restricted structure\n                               for sequence 1 (Will not generate other\n                               hotspots)",
  "      --r2=STRING            Specify the pseuodoknot-free restricted structure\n                               for sequence 2 (Will not generate other\n                               hotspots)",
  "      --t1=INT               Do not convert DNA into RNA. This will use the\n                               Matthews 2004 parameters for DNA  (default=`0')",
  "      --t2=INT               Do not convert DNA into RNA. This will use the\n                               Matthews 2004 parameters for DNA  (default=`0')",
  "  -p, --pen=DOUBLE           Specify the penalty for the interactions between\n                               the sequences",
  "  -n, --opt=INT              Specify the number of suboptimal structures to\n                               output (default is hotspot-num*hotspot-num)",
  "  -i, --input-file=STRING    Give a path to an input file containing the\n                               sequence (and input structure if known)",
  "  -o, --output-file=STRING   Give a path to an output file which will the\n                               sequence, and its structure and energy",
  "      --dir=STRING           Specify the directory for which each results will\n                               have a file",
  "  -k, --hotspot-num=INT      Specify the max number of hotspots per sequence\n                               (default is 20)  (default=`20')",
  "  -l, --hotspot-only=STRING  Specify the path to file to output the hotspots to",
  "  -d, --dangles=INT          Specify the dangle model to be used (base is 2)\n                               (default=`2')",
  "  -P, --paramFile1=STRING    Read energy parameters from paramfile, instead of\n                               using the default parameter set.",
  "  -Q, --paramFile2=STRING    Read energy parameters from paramfile, instead of\n                               using the default parameter set.",
  "  -B, --basePairFile=STRING  Takes a list of indices which will pair between\n                               sequences in the format a b with a being the\n                               index in sequence a and b in sequence b",
  "  -v, --varna=STRING         Specify the location for the VARNA jar",
  "      --micro                Treat the interaction as a microRNA:mRNA\n                               interaction and restricting pairing on bases 2-8\n                               in hotspot generation  (default=off)",
  "      --hard                 Treat the input structure as a hard constraint and\n                               only use method1 (HFold) for structure\n                               determination  (default=off)",
  "\nThe input sequence is read from standard input, unless it is\ngiven on the command line.\n",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_DOUBLE
} cmdline_parser_arg_type;

static
void clear_given (struct args_info *args_info);
static
void clear_args (struct args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->s1_given = 0 ;
  args_info->s2_given = 0 ;
  args_info->r1_given = 0 ;
  args_info->r2_given = 0 ;
  args_info->t1_given = 0 ;
  args_info->t2_given = 0 ;
  args_info->pen_given = 0 ;
  args_info->opt_given = 0 ;
  args_info->input_file_given = 0 ;
  args_info->output_file_given = 0 ;
  args_info->dir_given = 0 ;
  args_info->hotspot_num_given = 0 ;
  args_info->hotspot_only_given = 0 ;
  args_info->dangles_given = 0 ;
  args_info->paramFile1_given = 0 ;
  args_info->paramFile2_given = 0 ;
  args_info->basePairFile_given = 0 ;
  args_info->varna_given = 0 ;
  args_info->micro_given = 0 ;
  args_info->hard_given = 0 ;
}

static
void clear_args (struct args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->s1_arg = NULL;
  args_info->s1_orig = NULL;
  args_info->s2_arg = NULL;
  args_info->s2_orig = NULL;
  args_info->r1_arg = NULL;
  args_info->r1_orig = NULL;
  args_info->r2_arg = NULL;
  args_info->r2_orig = NULL;
  args_info->t1_arg = 0;
  args_info->t1_orig = NULL;
  args_info->t2_arg = 0;
  args_info->t2_orig = NULL;
  args_info->pen_orig = NULL;
  args_info->opt_orig = NULL;
  args_info->input_file_arg = NULL;
  args_info->input_file_orig = NULL;
  args_info->output_file_arg = NULL;
  args_info->output_file_orig = NULL;
  args_info->dir_arg = NULL;
  args_info->dir_orig = NULL;
  args_info->hotspot_num_arg = 20;
  args_info->hotspot_num_orig = NULL;
  args_info->hotspot_only_arg = NULL;
  args_info->hotspot_only_orig = NULL;
  args_info->dangles_arg = 2;
  args_info->dangles_orig = NULL;
  args_info->paramFile1_arg = NULL;
  args_info->paramFile1_orig = NULL;
  args_info->paramFile2_arg = NULL;
  args_info->paramFile2_orig = NULL;
  args_info->basePairFile_arg = NULL;
  args_info->basePairFile_orig = NULL;
  args_info->varna_arg = NULL;
  args_info->varna_orig = NULL;
  args_info->micro_flag = 0;
  args_info->hard_flag = 0;
  
}

static
void init_args_info(struct args_info *args_info)
{


  args_info->help_help = args_info_help[0] ;
  args_info->version_help = args_info_help[1] ;
  args_info->s1_help = args_info_help[2] ;
  args_info->s2_help = args_info_help[3] ;
  args_info->r1_help = args_info_help[4] ;
  args_info->r2_help = args_info_help[5] ;
  args_info->t1_help = args_info_help[6] ;
  args_info->t2_help = args_info_help[7] ;
  args_info->pen_help = args_info_help[8] ;
  args_info->opt_help = args_info_help[9] ;
  args_info->input_file_help = args_info_help[10] ;
  args_info->output_file_help = args_info_help[11] ;
  args_info->dir_help = args_info_help[12] ;
  args_info->hotspot_num_help = args_info_help[13] ;
  args_info->hotspot_only_help = args_info_help[14] ;
  args_info->dangles_help = args_info_help[15] ;
  args_info->paramFile1_help = args_info_help[16] ;
  args_info->paramFile2_help = args_info_help[17] ;
  args_info->basePairFile_help = args_info_help[18] ;
  args_info->varna_help = args_info_help[19] ;
  args_info->micro_help = args_info_help[20] ;
  args_info->hard_help = args_info_help[21] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(args_info_versiontext) > 0)
    printf("\n%s\n", args_info_versiontext);
}

static void print_help_common(void)
{
	size_t len_purpose = strlen(args_info_purpose);
	size_t len_usage = strlen(args_info_usage);

	if (len_usage > 0) {
		printf("%s\n", args_info_usage);
	}
	if (len_purpose > 0) {
		printf("%s\n", args_info_purpose);
	}

	if (len_usage || len_purpose) {
		printf("\n");
	}

	if (strlen(args_info_description) > 0) {
		printf("%s\n\n", args_info_description);
	}
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (args_info_help[i])
    printf("%s\n", args_info_help[i++]);
}

void
cmdline_parser_init (struct args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->s1_arg));
  free_string_field (&(args_info->s1_orig));
  free_string_field (&(args_info->s2_arg));
  free_string_field (&(args_info->s2_orig));
  free_string_field (&(args_info->r1_arg));
  free_string_field (&(args_info->r1_orig));
  free_string_field (&(args_info->r2_arg));
  free_string_field (&(args_info->r2_orig));
  free_string_field (&(args_info->t1_orig));
  free_string_field (&(args_info->t2_orig));
  free_string_field (&(args_info->pen_orig));
  free_string_field (&(args_info->opt_orig));
  free_string_field (&(args_info->input_file_arg));
  free_string_field (&(args_info->input_file_orig));
  free_string_field (&(args_info->output_file_arg));
  free_string_field (&(args_info->output_file_orig));
  free_string_field (&(args_info->dir_arg));
  free_string_field (&(args_info->dir_orig));
  free_string_field (&(args_info->hotspot_num_orig));
  free_string_field (&(args_info->hotspot_only_arg));
  free_string_field (&(args_info->hotspot_only_orig));
  free_string_field (&(args_info->dangles_orig));
  free_string_field (&(args_info->paramFile1_arg));
  free_string_field (&(args_info->paramFile1_orig));
  free_string_field (&(args_info->paramFile2_arg));
  free_string_field (&(args_info->paramFile2_orig));
  free_string_field (&(args_info->basePairFile_arg));
  free_string_field (&(args_info->basePairFile_orig));
  free_string_field (&(args_info->varna_arg));
  free_string_field (&(args_info->varna_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->s1_given)
    write_into_file(outfile, "s1", args_info->s1_orig, 0);
  if (args_info->s2_given)
    write_into_file(outfile, "s2", args_info->s2_orig, 0);
  if (args_info->r1_given)
    write_into_file(outfile, "r1", args_info->r1_orig, 0);
  if (args_info->r2_given)
    write_into_file(outfile, "r2", args_info->r2_orig, 0);
  if (args_info->t1_given)
    write_into_file(outfile, "t1", args_info->t1_orig, 0);
  if (args_info->t2_given)
    write_into_file(outfile, "t2", args_info->t2_orig, 0);
  if (args_info->pen_given)
    write_into_file(outfile, "pen", args_info->pen_orig, 0);
  if (args_info->opt_given)
    write_into_file(outfile, "opt", args_info->opt_orig, 0);
  if (args_info->input_file_given)
    write_into_file(outfile, "input-file", args_info->input_file_orig, 0);
  if (args_info->output_file_given)
    write_into_file(outfile, "output-file", args_info->output_file_orig, 0);
  if (args_info->dir_given)
    write_into_file(outfile, "dir", args_info->dir_orig, 0);
  if (args_info->hotspot_num_given)
    write_into_file(outfile, "hotspot-num", args_info->hotspot_num_orig, 0);
  if (args_info->hotspot_only_given)
    write_into_file(outfile, "hotspot-only", args_info->hotspot_only_orig, 0);
  if (args_info->dangles_given)
    write_into_file(outfile, "dangles", args_info->dangles_orig, 0);
  if (args_info->paramFile1_given)
    write_into_file(outfile, "paramFile1", args_info->paramFile1_orig, 0);
  if (args_info->paramFile2_given)
    write_into_file(outfile, "paramFile2", args_info->paramFile2_orig, 0);
  if (args_info->basePairFile_given)
    write_into_file(outfile, "basePairFile", args_info->basePairFile_orig, 0);
  if (args_info->varna_given)
    write_into_file(outfile, "varna", args_info->varna_orig, 0);
  if (args_info->micro_given)
    write_into_file(outfile, "micro", 0, 0 );
  if (args_info->hard_given)
    write_into_file(outfile, "hard", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (! args_info->s1_given)
    {
      fprintf (stderr, "%s: '--s1' option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  if (! args_info->s2_given)
    {
      fprintf (stderr, "%s: '--s2' option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  
  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_DOUBLE:
    if (val) *((double *)field) = strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_DOUBLE:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  /* TODO: Why is this here? It is not used anywhere. */
  override = params->override;
  FIX_UNUSED(override);

  initialize = params->initialize;
  check_required = params->check_required;

  /* TODO: Why is this here? It is not used anywhere. */
  check_ambiguity = params->check_ambiguity;
  FIX_UNUSED(check_ambiguity);

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "s1",	1, NULL, 0 },
        { "s2",	1, NULL, 0 },
        { "r1",	1, NULL, 0 },
        { "r2",	1, NULL, 0 },
        { "t1",	1, NULL, 0 },
        { "t2",	1, NULL, 0 },
        { "pen",	1, NULL, 'p' },
        { "opt",	1, NULL, 'n' },
        { "input-file",	1, NULL, 'i' },
        { "output-file",	1, NULL, 'o' },
        { "dir",	1, NULL, 0 },
        { "hotspot-num",	1, NULL, 'k' },
        { "hotspot-only",	1, NULL, 'l' },
        { "dangles",	1, NULL, 'd' },
        { "paramFile1",	1, NULL, 'P' },
        { "paramFile2",	1, NULL, 'Q' },
        { "basePairFile",	1, NULL, 'B' },
        { "varna",	1, NULL, 'v' },
        { "micro",	0, NULL, 0 },
        { "hard",	0, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVp:n:i:o:k:l:d:P:Q:B:v:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'p':	/* Specify the penalty for the interactions between the sequences.  */
        
        
          if (update_arg( (void *)&(args_info->pen_arg), 
               &(args_info->pen_orig), &(args_info->pen_given),
              &(local_args_info.pen_given), optarg, 0, 0, ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "pen", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* Specify the number of suboptimal structures to output (default is hotspot-num*hotspot-num).  */
        
        
          if (update_arg( (void *)&(args_info->opt_arg), 
               &(args_info->opt_orig), &(args_info->opt_given),
              &(local_args_info.opt_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "opt", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'i':	/* Give a path to an input file containing the sequence (and input structure if known).  */
        
        
          if (update_arg( (void *)&(args_info->input_file_arg), 
               &(args_info->input_file_orig), &(args_info->input_file_given),
              &(local_args_info.input_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "input-file", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Give a path to an output file which will the sequence, and its structure and energy.  */
        
        
          if (update_arg( (void *)&(args_info->output_file_arg), 
               &(args_info->output_file_orig), &(args_info->output_file_given),
              &(local_args_info.output_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "output-file", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'k':	/* Specify the max number of hotspots per sequence (default is 20).  */
        
        
          if (update_arg( (void *)&(args_info->hotspot_num_arg), 
               &(args_info->hotspot_num_orig), &(args_info->hotspot_num_given),
              &(local_args_info.hotspot_num_given), optarg, 0, "20", ARG_INT,
              check_ambiguity, override, 0, 0,
              "hotspot-num", 'k',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* Specify the path to file to output the hotspots to.  */
        
        
          if (update_arg( (void *)&(args_info->hotspot_only_arg), 
               &(args_info->hotspot_only_orig), &(args_info->hotspot_only_given),
              &(local_args_info.hotspot_only_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "hotspot-only", 'l',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Specify the dangle model to be used (base is 2).  */
        
        
          if (update_arg( (void *)&(args_info->dangles_arg), 
               &(args_info->dangles_orig), &(args_info->dangles_given),
              &(local_args_info.dangles_given), optarg, 0, "2", ARG_INT,
              check_ambiguity, override, 0, 0,
              "dangles", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'P':	/* Read energy parameters from paramfile, instead of using the default parameter set..  */
        
        
          if (update_arg( (void *)&(args_info->paramFile1_arg), 
               &(args_info->paramFile1_orig), &(args_info->paramFile1_given),
              &(local_args_info.paramFile1_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "paramFile1", 'P',
              additional_error))
            goto failure;
        
          break;
        case 'Q':	/* Read energy parameters from paramfile, instead of using the default parameter set..  */
        
        
          if (update_arg( (void *)&(args_info->paramFile2_arg), 
               &(args_info->paramFile2_orig), &(args_info->paramFile2_given),
              &(local_args_info.paramFile2_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "paramFile2", 'Q',
              additional_error))
            goto failure;
        
          break;
        case 'B':	/* Takes a list of indices which will pair between sequences in the format a b with a being the index in sequence a and b in sequence b.  */
        
        
          if (update_arg( (void *)&(args_info->basePairFile_arg), 
               &(args_info->basePairFile_orig), &(args_info->basePairFile_given),
              &(local_args_info.basePairFile_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "basePairFile", 'B',
              additional_error))
            goto failure;
        
          break;
        case 'v':	/* Specify the location for the VARNA jar.  */
        
        
          if (update_arg( (void *)&(args_info->varna_arg), 
               &(args_info->varna_orig), &(args_info->varna_given),
              &(local_args_info.varna_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "varna", 'v',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Specify the first sequence.  */
          if (strcmp (long_options[option_index].name, "s1") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->s1_arg), 
                 &(args_info->s1_orig), &(args_info->s1_given),
                &(local_args_info.s1_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "s1", '-',
                additional_error))
              goto failure;
          
          }
          /* Specify the second sequence.  */
          else if (strcmp (long_options[option_index].name, "s2") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->s2_arg), 
                 &(args_info->s2_orig), &(args_info->s2_given),
                &(local_args_info.s2_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "s2", '-',
                additional_error))
              goto failure;
          
          }
          /* Specify the pseuodoknot-free restricted structure for sequence 1 (Will not generate other hotspots).  */
          else if (strcmp (long_options[option_index].name, "r1") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->r1_arg), 
                 &(args_info->r1_orig), &(args_info->r1_given),
                &(local_args_info.r1_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "r1", '-',
                additional_error))
              goto failure;
          
          }
          /* Specify the pseuodoknot-free restricted structure for sequence 2 (Will not generate other hotspots).  */
          else if (strcmp (long_options[option_index].name, "r2") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->r2_arg), 
                 &(args_info->r2_orig), &(args_info->r2_given),
                &(local_args_info.r2_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "r2", '-',
                additional_error))
              goto failure;
          
          }
          /* Do not convert DNA into RNA. This will use the Matthews 2004 parameters for DNA.  */
          else if (strcmp (long_options[option_index].name, "t1") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->t1_arg), 
                 &(args_info->t1_orig), &(args_info->t1_given),
                &(local_args_info.t1_given), optarg, 0, "0", ARG_INT,
                check_ambiguity, override, 0, 0,
                "t1", '-',
                additional_error))
              goto failure;
          
          }
          /* Do not convert DNA into RNA. This will use the Matthews 2004 parameters for DNA.  */
          else if (strcmp (long_options[option_index].name, "t2") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->t2_arg), 
                 &(args_info->t2_orig), &(args_info->t2_given),
                &(local_args_info.t2_given), optarg, 0, "0", ARG_INT,
                check_ambiguity, override, 0, 0,
                "t2", '-',
                additional_error))
              goto failure;
          
          }
          /* Specify the directory for which each results will have a file.  */
          else if (strcmp (long_options[option_index].name, "dir") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->dir_arg), 
                 &(args_info->dir_orig), &(args_info->dir_given),
                &(local_args_info.dir_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "dir", '-',
                additional_error))
              goto failure;
          
          }
          /* Treat the interaction as a microRNA:mRNA interaction and restricting pairing on bases 2-8 in hotspot generation.  */
          else if (strcmp (long_options[option_index].name, "micro") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->micro_flag), 0, &(args_info->micro_given),
                &(local_args_info.micro_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "micro", '-',
                additional_error))
              goto failure;
          
          }
          /* Treat the input structure as a hard constraint and only use method1 (HFold) for structure determination.  */
          else if (strcmp (long_options[option_index].name, "hard") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->hard_flag), 0, &(args_info->hard_given),
                &(local_args_info.hard_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "hard", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
/* vim: set ft=c noet ts=8 sts=8 sw=8 tw=80 nojs spell : */
