/** @file cmdline.hh
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.23
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "DinoKnot"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "DinoKnot"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "1.0"
#endif

/** @brief Where the command line options are stored */
struct args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * s1_arg;	/**< @brief Specify the first sequence.  */
  char * s1_orig;	/**< @brief Specify the first sequence original value given at command line.  */
  const char *s1_help; /**< @brief Specify the first sequence help description.  */
  char * s2_arg;	/**< @brief Specify the second sequence.  */
  char * s2_orig;	/**< @brief Specify the second sequence original value given at command line.  */
  const char *s2_help; /**< @brief Specify the second sequence help description.  */
  char * r1_arg;	/**< @brief Specify the pseuodoknot-free restricted structure for sequence 1 (Will not generate other hotspots).  */
  char * r1_orig;	/**< @brief Specify the pseuodoknot-free restricted structure for sequence 1 (Will not generate other hotspots) original value given at command line.  */
  const char *r1_help; /**< @brief Specify the pseuodoknot-free restricted structure for sequence 1 (Will not generate other hotspots) help description.  */
  char * r2_arg;	/**< @brief Specify the pseuodoknot-free restricted structure for sequence 2 (Will not generate other hotspots).  */
  char * r2_orig;	/**< @brief Specify the pseuodoknot-free restricted structure for sequence 2 (Will not generate other hotspots) original value given at command line.  */
  const char *r2_help; /**< @brief Specify the pseuodoknot-free restricted structure for sequence 2 (Will not generate other hotspots) help description.  */
  int t1_arg;	/**< @brief Do not convert DNA into RNA. This will use the Matthews 2004 parameters for DNA (default='0').  */
  char * t1_orig;	/**< @brief Do not convert DNA into RNA. This will use the Matthews 2004 parameters for DNA original value given at command line.  */
  const char *t1_help; /**< @brief Do not convert DNA into RNA. This will use the Matthews 2004 parameters for DNA help description.  */
  int t2_arg;	/**< @brief Do not convert DNA into RNA. This will use the Matthews 2004 parameters for DNA (default='0').  */
  char * t2_orig;	/**< @brief Do not convert DNA into RNA. This will use the Matthews 2004 parameters for DNA original value given at command line.  */
  const char *t2_help; /**< @brief Do not convert DNA into RNA. This will use the Matthews 2004 parameters for DNA help description.  */
  double pen_arg;	/**< @brief Specify the penalty for the interactions between the sequences.  */
  char * pen_orig;	/**< @brief Specify the penalty for the interactions between the sequences original value given at command line.  */
  const char *pen_help; /**< @brief Specify the penalty for the interactions between the sequences help description.  */
  int opt_arg;	/**< @brief Specify the number of suboptimal structures to output (default is hotspot-num*hotspot-num).  */
  char * opt_orig;	/**< @brief Specify the number of suboptimal structures to output (default is hotspot-num*hotspot-num) original value given at command line.  */
  const char *opt_help; /**< @brief Specify the number of suboptimal structures to output (default is hotspot-num*hotspot-num) help description.  */
  char * input_file_arg;	/**< @brief Give a path to an input file containing the sequence (and input structure if known).  */
  char * input_file_orig;	/**< @brief Give a path to an input file containing the sequence (and input structure if known) original value given at command line.  */
  const char *input_file_help; /**< @brief Give a path to an input file containing the sequence (and input structure if known) help description.  */
  char * output_file_arg;	/**< @brief Give a path to an output file which will the sequence, and its structure and energy.  */
  char * output_file_orig;	/**< @brief Give a path to an output file which will the sequence, and its structure and energy original value given at command line.  */
  const char *output_file_help; /**< @brief Give a path to an output file which will the sequence, and its structure and energy help description.  */
  char * dir_arg;	/**< @brief Specify the directory for which each results will have a file.  */
  char * dir_orig;	/**< @brief Specify the directory for which each results will have a file original value given at command line.  */
  const char *dir_help; /**< @brief Specify the directory for which each results will have a file help description.  */
  int hotspot_num_arg;	/**< @brief Specify the max number of hotspots per sequence (default is 20) (default='20').  */
  char * hotspot_num_orig;	/**< @brief Specify the max number of hotspots per sequence (default is 20) original value given at command line.  */
  const char *hotspot_num_help; /**< @brief Specify the max number of hotspots per sequence (default is 20) help description.  */
  char * hotspot_only_arg;	/**< @brief Specify the path to file to output the hotspots to.  */
  char * hotspot_only_orig;	/**< @brief Specify the path to file to output the hotspots to original value given at command line.  */
  const char *hotspot_only_help; /**< @brief Specify the path to file to output the hotspots to help description.  */
  int dangles_arg;	/**< @brief Specify the dangle model to be used (base is 2) (default='2').  */
  char * dangles_orig;	/**< @brief Specify the dangle model to be used (base is 2) original value given at command line.  */
  const char *dangles_help; /**< @brief Specify the dangle model to be used (base is 2) help description.  */
  char * paramFile1_arg;	/**< @brief Read energy parameters from paramfile, instead of using the default parameter set..  */
  char * paramFile1_orig;	/**< @brief Read energy parameters from paramfile, instead of using the default parameter set. original value given at command line.  */
  const char *paramFile1_help; /**< @brief Read energy parameters from paramfile, instead of using the default parameter set. help description.  */
  char * paramFile2_arg;	/**< @brief Read energy parameters from paramfile, instead of using the default parameter set..  */
  char * paramFile2_orig;	/**< @brief Read energy parameters from paramfile, instead of using the default parameter set. original value given at command line.  */
  const char *paramFile2_help; /**< @brief Read energy parameters from paramfile, instead of using the default parameter set. help description.  */
  char * basePairFile_arg;	/**< @brief Takes a list of indices which will pair between sequences in the format a b with a being the index in sequence a and b in sequence b.  */
  char * basePairFile_orig;	/**< @brief Takes a list of indices which will pair between sequences in the format a b with a being the index in sequence a and b in sequence b original value given at command line.  */
  const char *basePairFile_help; /**< @brief Takes a list of indices which will pair between sequences in the format a b with a being the index in sequence a and b in sequence b help description.  */
  char * varna_arg;	/**< @brief Specify the location for the VARNA jar.  */
  char * varna_orig;	/**< @brief Specify the location for the VARNA jar original value given at command line.  */
  const char *varna_help; /**< @brief Specify the location for the VARNA jar help description.  */
  int micro_flag;	/**< @brief Treat the interaction as a microRNA:mRNA interaction and restricting pairing on bases 2-8 in hotspot generation (default=off).  */
  const char *micro_help; /**< @brief Treat the interaction as a microRNA:mRNA interaction and restricting pairing on bases 2-8 in hotspot generation help description.  */
  int hard_flag;	/**< @brief Treat the input structure as a hard constraint and only use method1 (HFold) for structure determination (default=off).  */
  const char *hard_help; /**< @brief Treat the input structure as a hard constraint and only use method1 (HFold) for structure determination help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int s1_given ;	/**< @brief Whether s1 was given.  */
  unsigned int s2_given ;	/**< @brief Whether s2 was given.  */
  unsigned int r1_given ;	/**< @brief Whether r1 was given.  */
  unsigned int r2_given ;	/**< @brief Whether r2 was given.  */
  unsigned int t1_given ;	/**< @brief Whether t1 was given.  */
  unsigned int t2_given ;	/**< @brief Whether t2 was given.  */
  unsigned int pen_given ;	/**< @brief Whether pen was given.  */
  unsigned int opt_given ;	/**< @brief Whether opt was given.  */
  unsigned int input_file_given ;	/**< @brief Whether input-file was given.  */
  unsigned int output_file_given ;	/**< @brief Whether output-file was given.  */
  unsigned int dir_given ;	/**< @brief Whether dir was given.  */
  unsigned int hotspot_num_given ;	/**< @brief Whether hotspot-num was given.  */
  unsigned int hotspot_only_given ;	/**< @brief Whether hotspot-only was given.  */
  unsigned int dangles_given ;	/**< @brief Whether dangles was given.  */
  unsigned int paramFile1_given ;	/**< @brief Whether paramFile1 was given.  */
  unsigned int paramFile2_given ;	/**< @brief Whether paramFile2 was given.  */
  unsigned int basePairFile_given ;	/**< @brief Whether basePairFile was given.  */
  unsigned int varna_given ;	/**< @brief Whether varna was given.  */
  unsigned int micro_given ;	/**< @brief Whether micro was given.  */
  unsigned int hard_given ;	/**< @brief Whether hard was given.  */

  char **inputs ; /**< @brief unnamed options (options without names) */
  unsigned inputs_num ; /**< @brief unnamed options number */
} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *args_info_purpose;
/** @brief the usage string of the program */
extern const char *args_info_usage;
/** @brief the description string of the program */
extern const char *args_info_description;
/** @brief all the lines making the help output */
extern const char *args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct args_info *args_info);
/**
 * Deallocates the string fields of the args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
